### ISSUE TITLE
amending rep entries

### ISSUE THREAD

**Issue by kikoorikoo** [phoneyourrep/phone-your-rep-api#8]
The DC fax # listed for Sen. Gillibrand is 202-225-1168. That is actually Rep John Faso’s DC Fax #. Gillibrand’s website lists her DC fax as (202) 228-0282

Rep. Maloney’s DC fax (missing) is 202-225-4709

Sen. Schumer’s DC fac (missing) is (202) 228-3027

Data missing for Rep. Hassan:
URL: https://www.hassan.senate.gov/
District offices:
1200 Elm Street
Suite 2
Manchester, NH 03101
Phone: (603) 622-2204

14 Manchester Square
Suite #140
Portsmouth, NH 03801
Phone: (603) 433-4445

Sen. Deb Fischer’s Scottsbluff office numbers are correct, but are also returned as her Omaha office info. Omaha numbers should be:
Phone: (402) 391-3411
Fax: (402) 391-4725

**Comment by kikoorikoo** [comment]
More info to add for Rep. Jack Bergman
url: http://bergman.house.gov/
Marquette, MI 49855 Phone: 906-273-2227
Traverse City, MI 49696 Phone: 231-944-7633

**Comment by msimonborg** [comment]
@kikoorikoo awesome, thanks for this! i'm pushing the updates right now. also added a bunch of other updates not listed here. please open another issue if you ever notice anything else
